data:
  input_file: "us_all_sectors_generation_monthly.csv"
  url: null
  date_col: "date"
  value_col: "value"
  resample_rule: null

model:
  max_difference_order: 2  # Number of differencing levels (e.g., 0,1,2)

plotting:
  figure_size: [12, 10]
  colors:
    - "k"
  linewidth: 1.8
  alpha: 0.9
  x_label: "Date"
  y_label: "Value"
  legend:
    frameon: false

plot_titles:
  base: "Global Surface Temperature Anomalies"
